// register user
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

// login user
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

// load user data
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// logout user
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

// delete user
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET"

// update user
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

// forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

// reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

// get user's watchlater
export const WATCHLATER_REQUEST = "WATCHLATER_REQUEST";
export const WATCHLATER_SUCCESS = "WATCHLATER_SUCCESS";
export const WATCHLATER_FAIL = "WATCHLATER_FAIL";

// add to watchlater
export const WATCHLATER_ADD_REQUEST = "WATCHLATER_ADD_REQUEST";
export const WATCHLATER_ADD_SUCCESS = "WATCHLATER_ADD_SUCCESS";
export const WATCHLATER_ADD_FAIL = "WATCHLATER_ADD_FAIL";

// remove from watchlater
export const WATCHLATER_REMOVE_REQUEST = "WATCHLATER_REMOVE_REQUEST";
export const WATCHLATER_REMOVE_SUCCESS = "WATCHLATER_REMOVE_SUCCESS";
export const WATCHLATER_REMOVE_FAIL = "WATCHLATER_REMOVE_FAIL";

// get user's history
export const HISTORY_REQUEST = "HISTORY_REQUEST";
export const HISTORY_SUCCESS = "HISTORY_SUCCESS";
export const HISTORY_FAIL = "HISTORY_FAIL";

// add to history
export const HISTORY_ADD_REQUEST = "HISTORY_ADD_REQUEST";
export const HISTORY_ADD_SUCCESS = "HISTORY_ADD_SUCCESS";
export const HISTORY_ADD_FAIL = "HISTORY_ADD_FAIL";

// remove from history
export const HISTORY_REMOVE_REQUEST = "HISTORY_REMOVE_REQUEST";
export const HISTORY_REMOVE_SUCCESS = "HISTORY_REMOVE_SUCCESS";
export const HISTORY_REMOVE_FAIL = "HISTORY_REMOVE_FAIL";

// get playlists
export const PLAYLIST_REQUEST = "PLAYLIST_REQUEST";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";
export const PLAYLIST_FAIL = "PLAYLIST_FAIL";

// create new playlist
export const PLAYLIST_ADD_REQUEST = "PLAYLIST_ADD_REQUEST";
export const PLAYLIST_ADD_SUCCESS = "PLAYLIST_ADD_SUCCESS";
export const PLAYLIST_ADD_FAIL = "PLAYLIST_ADD_FAIL";

// delete a playlist
export const PLAYLIST_REMOVE_REQUEST = "PLAYLIST_REMOVE_REQUEST";
export const PLAYLIST_REMOVE_SUCCESS = "PLAYLIST_REMOVE_SUCCESS";
export const PLAYLIST_REMOVE_FAIL = "PLAYLIST_REMOVE_FAIL";

// add to a playlist
export const PLAYLIST_VIDEO_ADD_REQUEST = "PLAYLIST_VIDEO_ADD_REQUEST";
export const PLAYLIST_VIDEO_ADD_SUCCESS = "PLAYLIST_VIDEO_ADD_SUCCESS";
export const PLAYLIST_VIDEO_ADD_FAIL = "PLAYLIST_VIDEO_ADD_FAIL";

// remove from a playlist
export const PLAYLIST_VIDEO_REMOVE_REQUEST = "PLAYLIST_VIDEO_REMOVE_REQUEST";
export const PLAYLIST_VIDEO_REMOVE_SUCCESS = "PLAYLIST_VIDEO_REMOVE_SUCCESS";
export const PLAYLIST_VIDEO_REMOVE_FAIL = "PLAYLIST_VIDEO_REMOVE_FAIL";

// clear errors
export const CLEAR_ERROR = "CLEAR_ERROR"

// clear messages
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"